FROM node:22 as builder

LABEL maintainer="info@redpencil.io"

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN DEPLOY_ENV=production npm run build

FROM semtech/static-file-service:0.1.0

COPY --from=builder /app/dist /data
