pipeline:
  install:
    image: danlynn/ember-cli:4.2.0-node_16.14
    commands:
      - npm ci
  lint:js:
    image: danlynn/ember-cli:4.2.0-node_16.14
    commands:
      - npm run lint:js
  lint:hbs:
    image: danlynn/ember-cli:4.2.0-node_16.14
    commands:
      - npm run lint:hbs
  lint:dependencies:
    image: danlynn/ember-cli:4.2.0-node_16.14
    commands:
      - npm run lint:dependencies
  test:
    image: danlynn/ember-cli:4.2.0-node_16.14
    commands:
      - npm run test:ember
when:
  event: pull_request